### ISSUE TITLE
Version 1.0 TO-DO list

### ISSUE THREAD

**Issue by deavmi** [deavmi/BoaGen#3]
- [x] [Create site generation example script](https://github.com/deavmi/BoaGen/issues/4)
- [x] Test version 1.0 (**v1.0**)
- [x] Do formal release using **GitHub Releases**
- [x] Create the **v1.0** branch

**Comment by deavmi** [comment]
**All is done!** :smile:
